### PR TITLE
ruby script using rbenv NOT a ppa

### PR DESCRIPTION
**Pull request by ncanderson**
Hi David, 
This is the best working ruby script I have. Uses rbenv, not the ppa. Takes longer to install but won't run into any issues with permissions I was having with the ppa. Compare this to the current ruby script.

Rails script will just sit right on top of whichever ruby script works the best. Rails install from packages takes < 5 min; the Ruby install is the biggest chunk. 

I pulled in all the changes from your develop branch before making this PR, and also pushed all the changes to my fork. Let me know if I should be doing something different - still learning how to use Git collaboratively!

-n

### CODE REVIEW

**Comment by davidmyersdev** [comment]
Hey. It looks like there are still some conflicts. I'm not sure exactly where they are yet, but GH is showing that they have to be resolved before the merge. I also wanted to see if you could revert any files that don't directly correspond with the Ruby/Rails scripts. I see a lot of files have been touched (.gitignore, scripts/base, scripts/php, all the test files). From what I can tell, there should only be 4 files to merge in (Vagrantfile, scripts/ruby, scripts/rails, and scripts/postgresql). 

In reality, these should actually be 3 different PRs (one for Rails, one for Ruby, and one for PostgreSQL), but I'm not going to worry too much about that right now. I definitely appreciate all the help, but I also want to make sure everything is merged in correctly to maintain a good state for the repo. :) 

Do you think you can take a look to see what might be going on? I'm going to look into cloning this branch and possibly merging it in manually. Thanks!

**Comment by davidmyersdev** [comment]
Ignore the previous comment! I was able to successfully merge everything into another branch (pr/nanderson83-rails) in this repo. I still need to verify everything before I merge it into develop, but you won't need to do anything now. Once I merge that new branch into develop, it should automatically close this PR. Thanks!

**Comment by ncanderson** [comment]
I am kind of flailing around I guess.

I made a test dir, and added it to gitignore, but I think it wasn't in the
gitignore that I actually submitted the PR for and ended up getting sucked
in. I was using php script for reference and probably touched the keyboard
on accident. Also I've been kind of working on Ruby and Rails together.

I can do a better job of keeping my PR cleaner. Did you get everything
sorted out?

Thoughts on PPA vs. building from rbenv?

On Wed, Apr 20, 2016 at 5:31 PM, David R. Myers II <notifications@github.com

**Comment by davidmyersdev** [comment]
Not a problem at all! I was able to get it all sorted out, but I just need to run some manual tests to make sure everything is working as expected before I actually merge it in. Make sure you don't push any more commits on your develop branch until I'm done with the merge though. 

Once I get it all merged in, you will need to make sure you get your fork up to date with my copy. If you have too many issues, you could always delete your current fork and then just create a new one. Make sure you wait until I'm completely finished with the PR merge though! 

As for the PPA, I do plan on looking into that some more, but I think we will be fine for now. Thanks!

**Comment by davidmyersdev** [comment]
After doing some testing, it looks like the new Ruby script is working, but the performance is lacking with `rbenv` (ruby 2.3.0 install took ~10 minutes). I'm doing some more research to see if I can do something about it, but if not, I might need to switch to `rvm` as it is much more performant (ruby 2.3.0 install took ~1 minute). 

Just keeping you posted!

**Comment by ncanderson** [comment]
I'm happy to do another script - I started with rbenv since it's what I
started with, and I was under the impression that it was lighter but if the
build time for Ruby is that much longer it would be worth checking out. It
would be interesting to see them side by side. When I get a minute I'll
thoroughly comment the ppa build and the issues I was having with it, so
you don't need to re-do anything I've done.

On Thu, Apr 21, 2016 at 5:19 PM, David R. Myers II <notifications@github.com

**Comment by davidmyersdev** [comment]
I've already tested the script with RVM, and it looks like the build time is closer to 4 minutes. Still a bit long, but much better so far. It also allows short versions such as 2.3 rather than explicit semantic versions such as 2.3.0. I am keeping your commits, but I've already added a bit myself, so make sure you don't commit anything to your develop branch. If you do want to work on it, make sure you create a new branch off of develop. You should be seeing your stuff merged in within the next day or two. I'm just about finished. Thanks!

**Pull request merged**
